export const GET_AUTHORS_REQUEST = "GET_AUTHORS_REQUEST";
export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
export const GET_AUTHORS_FAIL = "GET_AUTHORS_FAIL";
export const GET_AUTHORS_RESET = "GET_AUTHORS_RESET";

export const GET_AUTHOR_REQUEST = "GET_AUTHOR_REQUEST";
export const GET_AUTHOR_SUCCESS = "GET_AUTHOR_SUCCESS";
export const GET_AUTHOR_FAIL = "GET_AUTHOR_FAIL";
export const GET_AUTHOR_RESET = "GET_AUTHOR_RESET";

export const ADD_AUTHOR_REQUEST = "ADD_AUTHOR_REQUEST";
export const ADD_AUTHOR_SUCCESS = "ADD_AUTHOR_SUCCESS";
export const ADD_AUTHOR_FAIL = "ADD_AUTHOR_FAIL";
export const ADD_AUTHOR_RESET = "ADD_AUTHOR_RESET";

export const UPDATE_AUTHOR_REQUEST = "UPDATE_AUTHOR_REQUEST";
export const UPDATE_AUTHOR_SUCCESS = "UPDATE_AUTHOR_SUCCESS";
export const UPDATE_AUTHOR_FAIL = "UPDATE_AUTHOR_FAIL";
export const UPDATE_AUTHOR_RESET = "UPDATE_AUTHOR_RESET";

export const DELETE_AUTHOR_REQUEST = "DELETE_AUTHOR_REQUEST";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";
export const DELETE_AUTHOR_FAIL = "DELETE_AUTHOR_FAIL";
export const DELETE_AUTHOR_RESET = "DELETE_AUTHOR_RESET";
