export const GET_IMPRINTS_REQUEST = "GET_IMPRINTS_REQUEST";
export const GET_IMPRINTS_SUCCESS = "GET_IMPRINTS_SUCCESS";
export const GET_IMPRINTS_FAIL = "GET_IMPRINTS_FAIL";
export const GET_IMPRINTS_RESET = "GET_IMPRINTS_RESET";

export const GET_IMPRINT_REQUEST = "GET_IMPRINT_REQUEST";
export const GET_IMPRINT_SUCCESS = "GET_IMPRINT_SUCCESS";
export const GET_IMPRINT_FAIL = "GET_IMPRINT_FAIL";
export const GET_IMPRINT_RESET = "GET_IMPRINT_RESET";

export const ADD_IMPRINT_REQUEST = "ADD_IMPRINT_REQUEST";
export const ADD_IMPRINT_SUCCESS = "ADD_IMPRINT_SUCCESS";
export const ADD_IMPRINT_FAIL = "ADD_IMPRINT_FAIL";
export const ADD_IMPRINT_RESET = "ADD_IMPRINT_RESET";

export const UPDATE_IMPRINT_REQUEST = "UPDATE_IMPRINT_REQUEST";
export const UPDATE_IMPRINT_SUCCESS = "UPDATE_IMPRINT_SUCCESS";
export const UPDATE_IMPRINT_FAIL = "UPDATE_IMPRINT_FAIL";
export const UPDATE_IMPRINT_RESET = "UPDATE_IMPRINT_RESET";

export const DELETE_IMPRINT_REQUEST = "DELETE_IMPRINT_REQUEST";
export const DELETE_IMPRINT_SUCCESS = "DELETE_IMPRINT_SUCCESS";
export const DELETE_IMPRINT_FAIL = "DELETE_IMPRINT_FAIL";
export const DELETE_IMPRINT_RESET = "DELETE_IMPRINT_RESET";
