export const SET_SIGNIN_REQUEST = "SET_SIGNIN_REQUEST";
export const SET_SIGNIN_SUCCESS = "SET_SIGNIN_SUCCESS";
export const SET_SIGNIN_FAIL = "SET_SIGNIN_FAIL";
export const SET_SIGNIN_RESET = "SET_SIGNIN_RESET";

export const GET_SIGEDNOUT_USER_REQUEST = "GET_SIGEDNOUT_USER_REQUEST";
export const GET_SIGEDNOUT_USER_SUCCESS = "GET_SIGEDNOUT_USER_SUCCESS";
export const GET_SIGEDNOUT_USER_FAIL = "GET_SIGEDNOUT_USER_FAIL";
export const GET_SIGEDNOUT_USER_RESET = "GET_SIGEDNOUT_USER_RESET";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const GET_USERS_RESET = "GET_USERS_RESET";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_RESET = "GET_USER_RESET";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_USER_RESET = "ADD_USER_RESET";

export const PUT_USER_REQUEST = "PUT_USER_REQUEST";
export const PUT_USER_SUCCESS = "PUT_USER_SUCCESS";
export const PUT_USER_FAIL = "PUT_USER_FAIL";
export const PUT_USER_RESET = "PUT_USER_RESET";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const GET_ASSIGNEES_REQUEST = "GET_ASSIGNEES_REQUEST";
export const GET_ASSIGNEES_SUCCESS = "GET_ASSIGNEES_SUCCESS";
export const GET_ASSIGNEES_FAIL = "GET_ASSIGNEES_FAIL";
export const GET_ASSIGNEES_RESET = "GET_ASSIGNEES_RESET";
